package com.the.app


const val OPEN_LOCATION_NOTIFICATION_CLICK = "OPEN_LOCATION_NOTIFICATION_CLICK"
const val BUNDLE_KEY_FROM_SAVED_FOLDER = "BUNDLE_KEY_FROM_SAVED_FOLDER"
const val BUNDLE_KEY_INFO = "BUNDLE_KEY_INFO"
const val REQUEST_CODE_PERMISSION_LOCATION = 24
const val ZOOM_CHANGE_SIZE = 75
const val DATA_KEY_LOCATION = "DATA_KEY_LOCATION"
const val INTENT_SEND_LOCATION = "INTENT_SEND_LOCATION"
const val INTERVAL_LOCATION_REQUEST = 2000L
const val BUNDLE_KEY_ALBUM = "BUNDLE_KEY_ALBUM"
const val REQUEST_CODE_PERMISSION_WRITE_STORAGE = 23

